sudo: false
language: android

branches:
  only:
    - master

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

script:
  - ./gradlew :sample:test :sample:assembleDebug
